server:
  port:3698

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -id:
          uri:
          predicates:
            - Path=


