server:
  port: 808

spring:
  application:
    name: consumer

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.buck.demo.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"
