server:
  port: 80

spring:
  datasource:
    name: mysql
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://129.28.78.146:3306/spring
    username: root
    password: 2012dwDW
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  application:
    name: consumer

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.buck.demo.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"
