server:
  port: 3333
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/external-config
          search-paths:
            - ./
          default-label: master
          #username: xx 登?git??的??
          #password: yy 登?git??的密?

  application:
    name: config-server
  #profiles:
   # active:
    #  - develop #?种方式肯定不要用，用?境?量或者命令行????用：SPRING-PROFILES-ACTIVE=xx,yy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

---
spring:
  profiles: develop
  other-config: any config