server:
  port: 3333
spring:
  cloud:
    config:
      discovery:
        enabled: false
      server:
        git:
          uri: file://${user.home}/external-config
          search-paths:
            - ./
          default-label: master
          #username: xx
          #password: yy

  application:
    name: config-server
  #profiles:
   # active:
    #  - develop

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka

---
spring:
  profiles: develop
  other-config: any config