server:
  port: 8888

spring:
  application:
    name: producer
  cloud:
    config:
      uri: http://localhost:3333

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
